#!/bin/bash

# Case Study Image Download Helper Script
# This script helps you capture screenshots from the three websites

echo "==================================="
echo "Case Study Image Setup Helper"
echo "==================================="
echo ""
echo "This script will guide you through capturing screenshots for the case studies."
echo ""

# Define the target directory
TARGET_DIR="/Users/anisurrahman/Local Sites/portfolio/app/public/wp-content/themes/anisur-portfolio/assets/img/case-studies"

# Create directory if it doesn't exist
mkdir -p "$TARGET_DIR"

echo "Target directory: $TARGET_DIR"
echo ""
echo "Please follow these steps:"
echo ""
echo "1. Zone7 Official Website"
echo "   - Open https://zone7.co in your browser"
echo "   - Take a screenshot of the homepage (Cmd+Shift+4 on Mac)"
echo "   - Save it as: zone7.jpg"
echo "   - Move it to: $TARGET_DIR"
echo ""
echo "2. WPGigs Official Website"
echo "   - Open https://wpgigs.com/ in your browser"
echo "   - Take a screenshot of the homepage"
echo "   - Save it as: wpgigs.jpg"
echo "   - Move it to: $TARGET_DIR"
echo ""
echo "3. Cavenaugh Media"
echo "   - Open https://cavenaughmedia.com/ in your browser"
echo "   - Take a screenshot of the homepage"
echo "   - Save it as: cavenaughmedia.jpg"
echo "   - Move it to: $TARGET_DIR"
echo ""
echo "==================================="
echo "Quick Commands:"
echo "==================================="
echo ""
echo "To open the target directory in Finder:"
echo "open \"$TARGET_DIR\""
echo ""
echo "To check if images exist:"
echo "ls -lh \"$TARGET_DIR\"/*.jpg"
echo ""
echo "==================================="
echo "Image Optimization (Optional):"
echo "==================================="
echo ""
echo "After adding images, you can optimize them using ImageOptim or run:"
echo "# Install imagemagick if needed: brew install imagemagick"
echo "# Then optimize:"
echo "for img in \"$TARGET_DIR\"/*.jpg; do"
echo "  convert \"\$img\" -quality 85 -resize 800x600^ -gravity center -extent 800x600 \"\$img\""
echo "done"
echo ""
