<?php
/**
 * Portfolio Data Source
 *
 * Returns an array of portfolio items.
 */

function anisur_get_portfolio_items() {
	return array(
		array(
			'title'       => 'Zone7 Official Website',
			'description' => 'Modern corporate website built with Divi 5, featuring advanced page builder modules and premium design aesthetics.',
			'image'       => get_template_directory_uri() . '/assets/img/case-studies/zone7.svg',
			'link'        => 'https://zone7.co',
			'link_text'   => 'View Project →',
			'tags'        => array( 'DIVI 5', 'CORPORATE' ),
			'bg_color'    => '#1a1a2e',
		),
		array(
			'title'       => 'WPGigs Official Website',
			'description' => 'WordPress job marketplace built with Full Site Editing and custom Gutenberg blocks for maximum flexibility.',
			'image'       => get_template_directory_uri() . '/assets/img/case-studies/wpgigs.svg',
			'link'        => 'https://wpgigs.com/',
			'link_text'   => 'View Project →',
			'tags'        => array( 'GUTENBERG', 'FULL SITE EDITING' ),
			'bg_color'    => '#0d1b2a',
		),
		array(
			'title'       => 'Cavenaugh Media',
			'description' => 'Creative media agency website built with Elementor, showcasing dynamic layouts and custom widget integrations.',
			'image'       => get_template_directory_uri() . '/assets/img/case-studies/cavenaughmedia.svg',
			'link'        => 'https://cavenaughmedia.com/',
			'link_text'   => 'View Project →',
			'tags'        => array( 'ELEMENTOR', 'CREATIVE AGENCY' ),
			'bg_color'    => '#16213e',
		),
		array(
			'title'       => 'Back to Top',
			'description' => 'Simple and lightweight WordPress plugin for smooth scroll-to-top functionality.',
			'image'       => get_template_directory_uri() . '/assets/img/portfolio/back-to-top.png',
			'link'        => 'https://wordpress.org/plugins/ar-back-to-top/',
			'link_text'   => 'View Project →',
			'tags'        => array( 'PLUGIN', 'WORDPRESS.ORG' ),
			'bg_color'    => '#111821',
		),
		array(
			'title'       => 'Rashed Corp',
			'description' => 'A professional corporate WordPress website built with high-performance standards.',
			'image'       => get_template_directory_uri() . '/assets/img/portfolio/rashed-corp.png',
			'link'        => 'https://rashedcorp.co.uk/',
			'link_text'   => 'View Project →',
			'tags'        => array( 'WEB DESIGN', 'WORDPRESS' ),
			'bg_color'    => '#0d131a',
		),
		array(
			'title'       => 'Pastel Arabia',
			'description' => 'High-end WooCommerce store optimized for conversion and speed.',
			'image'       => get_template_directory_uri() . '/assets/img/portfolio/pastel-arabia.png',
			'link'        => 'https://pastelarabia.com/',
			'link_text'   => 'View Project →',
			'tags'        => array( 'E-COMMERCE', 'WOOCOMMERCE' ),
			'bg_color'    => '#111821',
		),
		array(
			'title'       => 'BootScore Theme',
			'description' => 'Active contributor to this popular Bootstrap 5 based WordPress starter theme.',
			'image'       => get_template_directory_uri() . '/assets/img/portfolio/bootscore.png',
			'link'        => 'https://github.com/bootscore/bootscore',
			'link_text'   => 'View Source →',
			'tags'        => array( 'OPEN SOURCE', 'BOOTSTRAP 5' ),
			'bg_color'    => '#0d131a',
		),
		array(
			'title'       => 'Popup Creator',
			'description' => 'Custom WordPress plugin for creating and managing highly customizable popups.',
			'image'       => get_template_directory_uri() . '/assets/img/portfolio/popup-creator.png',
			'link'        => 'https://github.com/anisur2805/arpc-popup-creator',
			'link_text'   => 'View Source →',
			'tags'        => array( 'PLUGIN', 'GITHUB' ),
			'bg_color'    => '#111821',
		),
		array(
			'title'       => 'Slack App Clone',
			'description' => 'Technical demonstration of a real-time messaging interface architecture.',
			'image'       => get_template_directory_uri() . '/assets/img/portfolio/slack-clone.png',
			'link'        => 'https://github.com/anisur2805/slack-clone',
			'link_text'   => 'View Source →',
			'tags'        => array( 'APP', 'SLACK CLONE' ),
			'bg_color'    => '#0d131a',
		),
		array(
			'title'       => 'WC Mini Cart',
			'description' => 'Enhanced WooCommerce mini-cart with AJAX plus/minus functionality.',
			'image'       => get_template_directory_uri() . '/assets/img/portfolio/wc-mini-cart.gif',
			'link'        => 'https://github.com/anisur2805/woocommerce-mini-cart-ajax-plus-minus',
			'link_text'   => 'View Source →',
			'tags'        => array( 'E-COMMERCE', 'AJAX' ),
			'bg_color'    => '#111821',
		),
		array(
			'title'       => 'WC Quick Order',
			'description' => 'High-efficiency quick order solution for bulk WooCommerce transactions.',
			'image'       => get_template_directory_uri() . '/assets/img/portfolio/wc-quick-order.svg',
			'link'        => 'https://github.com/anisur2805/quick-order-for-woocommerce',
			'link_text'   => 'View Source →',
			'tags'        => array( 'PLUGIN', 'WOOCOMMERCE' ),
			'bg_color'    => '#0d131a',
		),
		array(
			'title'       => 'Pastel Bangladesh',
			'description' => 'Localized e-commerce experience for the Bangladesh market with optimized performance.',
			'image'       => get_template_directory_uri() . '/assets/img/portfolio/pastel-bangladesh.png',
			'link'        => 'https://pastelbangladesh.com/',
			'link_text'   => 'View Project →',
			'tags'        => array( 'E-COMMERCE', 'WOOCOMMERCE' ),
			'bg_color'    => '#111821',
		),
		array(
			'title'       => 'Global One',
			'description' => 'A high-impact donation platform designed for global outreach and reliability.',
			'image'       => get_template_directory_uri() . '/assets/img/portfolio/global-one.png',
			'link'        => 'https://global-one.com/',
			'link_text'   => 'View Project →',
			'tags'        => array( 'NON-PROFIT', 'DONATION' ),
			'bg_color'    => '#0d131a',
		),
		array(
			'title'       => 'Smooth Move Removal',
			'description' => 'A service-based WordPress website with custom booking and service integrations.',
			'image'       => get_template_directory_uri() . '/assets/img/portfolio/smooth-move.png',
			'link'        => 'https://smoothmoveremovals.com.au/',
			'link_text'   => 'View Project →',
			'tags'        => array( 'SERVICES', 'WORDPRESS' ),
			'bg_color'    => '#111821',
		),
	);
}
